### ISSUE TITLE
the 'google' package in requirements.txt

### ISSUE THREAD

**Issue by ghost** [darcosion/limier#3]
https://github.com/darcosion/limier/blob/master/requirements.txt

>robobrowser
>google

Fedora wasn't able to install the dependencies:

```
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
```

I assume that you're using a `googlesearch` package from [the Python index](https://pypi.org/search/?q=googlesearch)?

`robobrowser` I installed with `pip`: https://pypi.org/project/robobrowser/

**Comment by darcosion** [comment]
Hello, 

> https://github.com/darcosion/limier/blob/master/requirements.txt
> 
> > robobrowser
> > google
> 
> Fedora wasn't able to install the dependencies:

Thanks for the information ! 

> I assume that you're using a `googlesearch` package from [the Python index](https://pypi.org/search/?q=googlesearch)?

No, this is the `google` package : https://pypi.org/project/google/

> `robobrowser` I installed with `pip`: https://pypi.org/project/robobrowser/

Be careful for your python compatibility, pip could be different of pip3.

Regards
